### ISSUE TITLE
Python3.9 incompatibility

### ISSUE THREAD

**Issue by smarek** [rshk/python-pcapng#38]
Seems like there is some incompatibility, since Python3.9 deprecated fractions.gcd in favor of math.gcd function, see the stacktrace below

```
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
WARNING: can't import layer ipsec: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/pcapng/structs.py", line 562, in _get_raw
    return self.raw_data[_name][0]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.9/site-packages/hytera_homebrew_bridge-2021.1-py3.9.egg/hytera_homebrew_bridge/tests/pcap_test.py", line 270, in <module>
    pprint_enhanced_packet(block)
  File "/home/user/.local/lib/python3.9/site-packages/hytera_homebrew_bridge-2021.1-py3.9.egg/hytera_homebrew_bridge/tests/pcap_test.py", line 137, in pprint_enhanced_packet
    col256(str(block.interface.options["if_name"]), fg="140"),
  File "/home/user/.local/lib/python3.9/site-packages/pcapng/structs.py", line 490, in __getitem__
    return self._get_converted(name)
  File "/home/user/.local/lib/python3.9/site-packages/pcapng/structs.py", line 574, in _get_converted
    value = self._get_raw(name)
  File "/home/user/.local/lib/python3.9/site-packages/pcapng/structs.py", line 564, in _get_raw
    raise KeyError(name)
KeyError: 'if_name'

```

**Comment by bbenne10** [comment]
gcd has nothing to do with this - I suspect that this is from scapy rather than from pcapng. I'm not entirely sure what is happening during parsing though. (clearly the key `2` is not in `self.raw_data` here, but I'm not sure how to debug this without some more information about how you invoked this)

We are using this library just fine with python3.9 locally. I'm inclined to say that this is invalid (or some other bug unrelated to 3.9+)

**Comment by smarek** [comment]
Hey, thanks, i'll close this, since it's been so long, i'm not currently able to tell you more details. 
Maybe from at-the-time commited version of hytera-homebrew-bridge, but since, it's gone through so much development, i don't think it'll be useful for anyone, to investigate it.
Current implementation moved from HHB to [ok-dmrlib](https://github.com/OK-DMR/ok-dmrlib) depends on scapy+numpy, so there is no need to investigate just for the sake of this report. Ref. https://github.com/OK-DMR/ok-dmrlib/blob/master/okdmr/dmrlib/tools/pcap_tool.py#L23

Thank you Bryan, and good luck with your project
