### ISSUE TITLE
get wrong

### ISSUE THREAD

**Issue by ccfasm** [rshk/python-pcapng#9]
```
Traceback (most recent call last):

  File "<ipython-input-2-7de0134592f5>", line 1, in <module>
    runfile('E:/pycode/ipv6/flow.py', wdir='E:/pycode/ipv6')

  File "D:\WinPython-32bit-2.7.9.4\python-2.7.9\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "D:\WinPython-32bit-2.7.9.4\python-2.7.9\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "E:/pycode/ipv6/flow.py", line 14, in <module>
    for block in scanner:

  File "D:\WinPython-32bit-2.7.9.4\python-2.7.9\lib\site-packages\pcapng\scanner.py", line 40, in __iter__
    yield self._read_next_block()

  File "D:\WinPython-32bit-2.7.9.4\python-2.7.9\lib\site-packages\pcapng\scanner.py", line 54, in _read_next_block
    raise ValueError('File not starting with a proper section header')

ValueError: File not starting with a proper section header
```

**Comment by rshk** [comment]
Hi, it looks like you were trying to parse a file which is not in pcap-ng format?

Can you send me a sample of the file, eg by running:

```python
with open('E:/path/to/data.pcapng', 'rb') as fp:
    data = fp.read(100)

print(repr(data))
```

**Comment by rshk** [comment]
I'm closing this. Please reopen (with more details) if you believe this is still a bug.
